### ISSUE TITLE
calling a function with default parameters breaks compilation

### ISSUE THREAD

**Issue by parallelno** [GaijinEntertainment/daScript#160]
Hi! The code below cases a compile error
-------------------------------------------------------
class TestClass
    def Test(i : int = -1) : int
        return -1

[export]
def main
    var tc = new TestClass()
    let i : int = tc->Test()

.code.tio:8:20:
    let i : int = tc->Test()
                    ^^
20:8 - 21:8
30301: casting to undefined type auto
-------------------------------------------------------
I suppose tc->Test() should be compiled fine because Test function has a default parameter -1

**Comment by borisbat** [comment]
I've added extra error message to indicate invalid number of arguments. 

The issue here is that class member functions are by definition 'virtual' and the default value could be different from base class to the derived class. So all arguments need to be specified explicitly.
The reason we allow default arguments at all is that macros can explicitly access them for miscellaneous purposes.
Potentially we can look into using 'current type's default value' as default, but that does not seem explicit enough. I.e. function can be inherited and all that.

**Comment by parallelno** [comment]
Does that mean that dascript can't support default parameters same way they work in python, c++, c#?

**Comment by AntonYudintsev** [comment]
dascript can support default parameters for common functions, same way as c++ (actually better, as it allows calling with named arguments).
def foo2(a:int; b: int=3)
    return a + b

def foo(a:int=13; b: int)
    return a + b

def bar
    foo([b = 2])  // same as foo(13, 2)
    foo2(2)  // same as foo2(2, 3)

see https://dascript.org/doc/reference/language/functions.html?highlight=default%20arguments#function-declaration

But that is not the case for class virtual functions.
