### ISSUE TITLE
Automated C++ integration?

### ISSUE THREAD

**Issue by brjoha** [GaijinEntertainment/daScript#231]
Has there been any thought given to creating a companion tool that will parse C++ header files to ease embedding daScript into an application?  Better yet, add daScript support to SWIG (www.swig.org) and expose it to a wider community.

Reference http://www.swig.org/Doc4.0/SWIGDocumentation.html#Extending

**Comment by borisbat** [comment]
there is a script which i use to bind modules. examples are in /modules/dasGlfw, /modules/dasBGX, /modules/dasImgui etc
it utilizes calng's export ast feature (which is not particulally stable)
on the up side it allows to get ~80%-99% there, with hardly any work
on the down side its not fully automated - and i'm somewhat certain that full automation would be very hard to achive with just about any autobind

integrating swig looks like a good idea. worth considering, given bandwidth. i'll gladly help whoever is up to the challenge, otherwise i might get to it one day

one feature, which is upcoming shortly, is [extern_c] annotation, where a function name and a dll is specified - and would be bound dynamically. if anything its a lot more gentle with the compilation time, which now seems like a growing problem

**Comment by borisbat** [comment]
And we are there.
dasGLFW, dasBGFX, dasImgui, dasClangBind, dasOpenGL - are now fully generated with the new generator, based on dasClangBind
there are 2 generator options - [extern] based and proper C++ binding based
use it, abuse it
