### ISSUE TITLE
Infrastructure Documentation / Meta Documentation

### ISSUE THREAD

**Issue by rburkholder** [GaijinEntertainment/daScript#627]
I've seen quite a bit of documentation on the language, and on some of the requirements for embedding the scripts within C++.

I have read through the tutorials in [tutorials](examples/tutorial), but they seem to refer to single use efforts. 

In my project, I want to use a script repeatedly.  tutorial6 hints at one mechanism to do this through repeated calls to a method.  Is that the best practices approach: encapsulate the script in a class, and call it as an object?

Based upon a re-use error I am getting (builtin module not found? or you have forgotten to NEED_MODULE(Module_BuiltIn) be called first), for each script that is activated, does it require the 
`
NEED_ALL_DEFAULT_MODULES; das::Module::Initialize(); das::Module::Shutdown();` decorators for each ContextPtr/ProgramPtr pair?

but.... das::Module::Initialize and das::Module::Shutdown are static functions, implying they should only be used once.  So... how do I get around the requirement for the NEED... followed by the Initialize for multiple scripts?

In addition, I can't seem to find information on what program->simulate does and why it is needed.

One other item: what is das::TextPrinter?   Can I subsititue my own print/output stuff (for instance how would I use Boost::Trivial_Log or std::cout or similar?

edit:  I can't seem to run this more than once in a program:
`das::ProgramPtr pProgram = das::compileDaScript( sPath, pAccess, tout, *m_pModuleGroup );`

**Comment by borisbat** [comment]
Ok. Lets start in the middle. program->simualte creates Context - which is an instance of a program, which can be executed. It contains the code, constants, variables, etc. Context can be cloned. There can be multiple instances of multiple different Context's in the same application.

Once simulated Program is no longer necessary and can be deleted (unless "options rtti" is used, or program is kept for metaprogramming purposes). Basically Program contains compiled version of a program, AST, type information, etc,etc - and Context is an instance of a running program. 

There is compiler environment which is unique per thread. Its created via Module::Initialize and destroyed via Module::Shutdown. NEED_MODULE creates list of builtin modules, which are bound to the environment. All compilation and evaluation at runtime require live environment.

Tutorial06 demonstrates that Context can be viewed as an instance of the 'class', which is defined via daScript program. SimFunction * pointers to methods can be obtained, and repeatedly called. Context preserves state between calls (or its state can be reset). Thats one approach. It requires "options persistent_heap" and likely calling GC::collect on the context of from inside the context every so often.

Context class can be derived from, and compiler can use derived context. That way implementation can be kept in one class instead and more importantly macros can access custom data during compilation.

We had a lot of success another approach, where state is stored on C++ side (via ECS and otherwise). And we 'reset' context after every call of the method. In that mode we use linear memory allocator, and reset effectively serves as 0-cost garbage collector.

Larger applications will likely require both approaches - where some sections are ecs+0-gc updates, and some store state on the daScript side.

das::TextPrinter is there for the purposes of outputing compiler log to the console. You can dervie from das::TextWriter, override 'output' function, and pass that to "log". Additionally there is runtime logging infrastructure in the context which can also be overwritten.

**Comment by borisbat** [comment]
https://t.me/daScript telegram channel for daScript. It would probably be easier to iterate there vs over comments to the issue.

In your implementation moduleGroup is shared between scripts, and its likely causing problems. Thing to do is to create module group for each program, and delete it after.

https://github.com/GaijinEntertainment/daScript/blob/master/examples/test/main.cpp - bool unit_test ( const string & fn, bool useAot ) - compiles, runs, and deletes a script safely. FileAccess can be shared, everything else does not.

Thread Local Storage is significant. If compiled from multiple threads Module::Initialize and Module::Shutdown need to be called for each compiling thread. If all scripts are compiled ahead of time, they can be called from multiple threads - but environment from the main thread needs to be bound to each unique thread. Again compilation in multiple threads is at the same link above.
