### ISSUE TITLE
Does not compile using c++ 17 on msvc

### ISSUE THREAD

**Issue by emelrad12** [GaijinEntertainment/daScript#77]
Tried compiling path tracer, and creating new project, both cases, only compile using cpp 14.

**Comment by thagberg** [comment]
I had this issue with MSVC and was able to solve it with this in `misc/platform.h`:
```
#if defined(_MSC_VER) && !defined(__clang__)
#if !defined(_MSVC_LANG) || _MSVC_LANG < 201703L
__forceinline uint32_t __builtin_clz(uint32_t x) {
    unsigned long r = 0;
    _BitScanReverse(&r, x);
    return uint32_t(31 - r);
}
#endif
#endif
```

`__builtin_clz` appears to be defined for C++17 in MSVC, so this prevents it from being redefined.

**Comment by AlvaroBarua** [comment]
Hi, sorry to comment on a closed issue, but I just changed my project from c++14 to c++17 for a test and I am getting '__builtin_clz' not found.
I am using VS2019 Community Edition.

I had to revert the changes made here so that it compiles. Not sure what to make of it to be honest, but from what I tested, __builtin_clz is nowhere to be found in MSVC17 or MSVC20.

**Comment by thagberg** [comment]
After a VS update I started seeing the same thing, but I've been unable to find anything in release notes to pin down what changed.

**Comment by AlvaroBarua** [comment]
I guess that it could have been a fluke in MSVC at the time or something with the use case at the time you tested.
Just to make sure, I tried on an empty project and still the same result. 
It might be good to revert this change and see if anyone gets an error in the future.
