### ISSUE TITLE
Does it support passing string/blob objects by zero-copy?

### ISSUE THREAD

**Issue by asbai** [GaijinEntertainment/daScript#86]
Dascript is a performance-oriented scripting language. As we all know, the memory copy and encoding conversion caused by the parameter transfer between Native Code and Script are important factors that slow down the overall performance of the script.

Therefore, does dascript currently support zero-copy transfer of string / blob and other types of parameters between Natvie Code and Script?

AFAIK, AngleScript can support this type of optimization. In AngleScript, the string and blob types used by the script can be implemented by the developer. Therefore, as long as the string and blob types used by developers in Native Code support reference counting and copy-on-write, these parameters can be passed between the script and Native Code in a zero-copy manner.

I wonder if daScript also supports such optimization?

Thanks :-)

**Comment by AntonYudintsev** [comment]
Hello
Since daScript allows binding of any handled (external) types, and working with them by reference - the answer is "yes, ofc"
It is actually much, much harder to implement "copy" transfer then "zero-copy", as all daScript functions accepts all non-POD types only by references, so it is really not that easy to make copying functions.

Also, by default both strings type and functions working with it ("string", which is const char*, immutable string; and das_string, mutable string which is "std::string") are binded with zero-copy (which is obvious, since they work with references).
"blob type" (which will be vector or dynamic array in daScript) follows the same logic.

daScript doesn't support copy-on-write in it's types, and it is not that simple to find a generic case where it would be done correctly and still provide some benefits; but there is nothing that disallows someone to bind their one copy-on-write, immutable, ref-counted, or any other type.

It is also possible to work with daScript GC (instead of ref-counting), and keep state there.

Problems can arouse when the ownership isn't clear - i.e. when state and references to it are stored in both host environment (c++) and in script VM.
That's just messy, don't do it in any scripting language! :)
Either use script as state owner and work with it from c++ using exported functions; or use c++ hosted state and work with it from script using das functions accepting references or binded c++ functions providing references.
The former way allows GC, and VScode LSP plugin for daScript is written this way.
The latter way allows extremely fast memory-management in script (basically perf-frame / per-call bump-allocator) and "stateless", pure functional (in a sense) scripts. That's how all our game scripts are written.

**Comment by asbai** [comment]
AntonYudintsev, thank you for the detailed and kindly reply :)

Since our types such as string and blob in C++ already have built-in reference counting mechanism, can it be considered also allows non-POD types to be registered as a "by value type" (allowing users to define the constructor/destructor, copy/assignment operations and alignment details, just like AngleScript)? 

This can reduce a pair of new / delete operation for each instance (we can create string / blob objects on the host's stack instead of on the heap, and then pass them to the vm). It's further increasing efficiency.

PS: Can we replace the underlying implementation of das_string from std::string to our own string type without hacking the source code? :-)
